(function(){
var isIE = window.navigator.userAgent.indexOf("MSIE ") > 0;
var ifr = "<"+"iframe id=\"cto_iframe_cfed3edd74\" frameBorder=\"0\" allowtransparency=\"true\" hspace=\"0\" marginwidth=\"0\" marginheight=\"0\" scrolling=\"no\" vspace=\"0\" width=\"300px\" height=\"250px\"\n";
if(isIE && document.domain !== window.location.hostname) {
ifr += " src=\"javascript:'<script>window.onload=function(){document.write(\\\'<script>document.domain = &quot;"+document.domain + "&quot;;<\\\\/script>\\\');document.close();};</script>'\"";
}
ifr += "><"+"/iframe>\n";
document.write(ifr);
var ifc = "\n";
ifc += "<"+"!DOCTYPE html>\n";
ifc += "<"+"html>\n";
ifc += "  <"+"head>\n";
ifc += "    <"+"meta name=\"format-detection\" content=\"telephone=no\"><"+"meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\n";
ifc += "  <"+"/head>\n";
ifc += "  <"+"body><"+"div id=\'cto_banner_content\'><"+"style>\n";
ifc += "#cto_products .cto_product .imgholder{ text-align : center; background : #ffffff; float : left; margin-right : 7px; width : 74px; height : 74px;\n";
ifc += "} #cto_products .cto_product .imgholder img{ border : none; max-width : 74px; max-height : 74px; *width : expression(this.width >= this.height ? \"74px\" : \"auto\"); *height : expression(this.width <"+" this.height ? \"74px\" : \"auto\");\n";
ifc += "} #cto_products .cto_product .title{ overflow : hidden; color : #016090; font-size : 14px; height : 18px; line-height : 16px; font-weight : bold;\n";
ifc += "} #cto_products .cto_product .desc{ overflow : hidden; color : #646464; font-size : 12px; height : 30px; line-height : 14px;\n";
ifc += "} #cto_products .cto_product .priceDesc{ color : #FF9900; font-size : 16px; height : 24px; line-height : 20px; font-weight : bold;\n";
ifc += "} #cto_products .cto_product .priceDesc .origPrice{ color : #999; font-size : 13px; height : 18px; line-height : 16px; font-weight : normal;\n";
ifc += "} #cto_products .cto_product:hover{ background : #eeeeee;\n";
ifc += "} #cto_products .cto_product .details{ float : left; width : 217px;\n";
ifc += "} #cto_products .cto_product *{ *cursor : pointer;\n";
ifc += "} #cto_products .cto_product a{ color : black; text-decoration : none;\n";
ifc += "} #cto_bannerContent{ width : 300px; height : 250px; background : #ffffff; position : relative; font-family : Arial,sans-serif; font-size : 0; overflow : hidden;\n";
ifc += "} #cto_products{ height : 233px; width : 300px; overflow : hidden;\n";
ifc += "} #cto_products .cto_product{ width : 298px; height : 74px; float : left; text-align : left; overflow : hidden; vertical-align : top; zoom : 1; position : relative; *zoom : 1; *display : inline; margin : 1px 1px 3px 1px;\n";
ifc += "} #cto_bannerContent .footer{ height : 17px; line-height : 16px; position : relative; text-align : left;\n";
ifc += "} #cto_bannerContent .adUrl{ font-size : 11px; color : #808080; text-decoration : none; cursor : pointer; *cursor : pointer; zoom : 1; vertical-align : top; margin-right : 4px; display : inline-block; *display : inline; margin-left : 4px; line-height : 17px;\n";
ifc += "} #cto_bannerContent .adUrl:hover{ text-decoration : underline;\n";
ifc += "} #cto_bannerContent .legal{ text-overflow : ellipsis; white-space : nowrap; overflow : hidden; font-size : 11px; color : #808080; display : inline-block; *display : inline; height : 16px; width : 100px;\n";
ifc += "} #cto_bannerContent .legalover{ position : absolute; left : 1px; box-sizing : border-box; font-size : 11px; color : #808080; text-decoration : none; display : block; zoom : 1; padding : 4px; background : #eee; opacity : 0.95; filter : alpha(opacity=95); visibility : hidden; line-height : 12px; width : 300px; bottom : 1px;\n";
ifc += "} <"+"/style>\n";
ifc += "<"+"div id=\"cto_bannerContent\">\n";
ifc += "<"+"div id=\"cto_products\">\n";
ifc += "\n";
ifc += "<"+"div class=\"cto_product\">\n";
ifc += "<"+"a href=\"http://cat.nl.eu.criteo.com/delivery/ck.php?cppv=1&cpp=owzw8XxFUlIxN0tPbWl6dW9RWkd2bWpKZEIzbWR0Y3c3TW54aUVCMmtXa0d6cWRTSzNHUStSNG9ha1A3RmY2N2Y4R2djZ29idFRuK3lnempmNVhSekU2MHhseS9jdUc0cHB4OHBtVjFJWVZmRjdpdm5HeURSbUN1dnFMU1JzTXMxNm5VUmlHVFk4ZmpFOVhlWEkvWGpKbFlDRzk3Vms3SXhzeVNMSitmZHNiWmZYNkVHcFFDcXBvSGFmdEdOUHo3MXV3Ulk5UzZGelZDZ2p6MXBub3hMOHBzWithUmJSL21MMm1yaTliRklrK1dySmd5TVVkY0pRSGhXcDlHQzQwSHZMQVdOUTdTaW9kRnhna2MxaStKQkhTS3RBM1lqZ3BZQmRHc3pIR1h1NDFWZ0Fiaz18&maxdest=http%3A%2F%2Fwww.morele.net%2Fpamiec-pamiec-hyperx-savage-ddr4-2x8gb-3000mhz-cl15-hx430c15sb2k2-16-842724%2F%3Futm_source%3Dcriteo.com%26utm_medium%3Dbaner%26utm_content%3D300x250%26utm_campaign%3Dremarketing_criteo\" target=\"_blank\" >\n";
ifc += "<"+"div class=\"imgholder\">\n";
ifc += "<"+"img src=\"http://pix.nl.eu.criteo.net/img/img?c=1&cb=1&h=400&i=15285-842724&m=0&q=80&r=0&u=https%3A%2F%2Fimages.morele.net%2Fi256%2F842724_0_i256.jpeg&w=400&s=zt_a0QuvdMWzgj57NNP2aWfs\">\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div class=\"details\">\n";
ifc += "<"+"div class=\"title\" data-ellipsis=\"multiline\">Pami&#281;&#263; HyperX Savage DDR4, 2x8GB,  3000MHz,  CL15 (HX430C15SB2K2/16) Szybka dostawa!  Darmowy odbi&#243;r w 19 miastach! Raty od 17,00 z&#322;<"+"/div>\n";
ifc += "<"+"div class=\"desc\" data-ellipsis=\"multiline\"><"+"/div>\n";
ifc += "<"+"div class=\"priceDesc\">\n";
ifc += "<"+"span class=\"priceType\">rrp<"+"/span>\n";
ifc += "<"+"del class=\"origPrice\"><"+"/del>\n";
ifc += "<"+"span class=\"price\">439 z&#322;<"+"/span>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/a>\n";
ifc += "<"+"/div>\n";
ifc += "\n";
ifc += "<"+"div class=\"cto_product\">\n";
ifc += "<"+"a href=\"http://cat.nl.eu.criteo.com/delivery/ck.php?cppv=1&cpp=zifEJXxFUlIxN0tPbWl6dW9RWkd2bWpKZEIzbWR0Y3c3TW54aUVCMmtXa0d6cWRTSzNHUStSNG9ha1A3RmY2N2Y4R2djZ29idFRuK3lnempmNVhSekU2MHhseS9jdUc0cHB4OHBtVjFJWVZmRjdpdm5HeURSbUN1dnFMU1JzTXMxNm5VUmlHVFk4ZmpFOVhlWEkvWGpKbFlDRzlpRjJGREd0RHJwUnpxU2RadnZ3eHcrclU1M3dvYk5OTUNaaEVqZEZvck9IZDY3OXBTY1FyTEtwMSsra25SMDRRVnEvYTZyVC9QczA3a08rT2YwZ1d2c3FnQ1phUmxOU1ZXTTNSOUFGcjFqdU9xSzIrVGh3MERMSVRadGViQldQNUhaOHcwd2VQcUNabHBGUk5WMkFTOD18&maxdest=http%3A%2F%2Fwww.morele.net%2Fdysk-ssd-dysk-ssd-crucial-mx200-250gb-sata3-ct250mx200ssd6-712714%2F%3Futm_source%3Dcriteo.com%26utm_medium%3Dbaner%26utm_content%3D300x250%26utm_campaign%3Dremarketing_criteo\" target=\"_blank\" >\n";
ifc += "<"+"div class=\"imgholder\">\n";
ifc += "<"+"img src=\"http://pix.nl.eu.criteo.net/img/img?c=1&cb=1&h=400&i=15285-712714&m=0&q=80&r=0&u=https%3A%2F%2Fimages.morele.net%2Fi256%2F712714_0_i256.jpg&w=400&s=nAJ6-umSLmA77ZYUCniH2dVq\">\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div class=\"details\">\n";
ifc += "<"+"div class=\"title\" data-ellipsis=\"multiline\">Dysk SSD Crucial MX200 250GB SATA3 (CT250MX200SSD6) Darmowy odbi&#243;r w 19 miastach! Raty od 16,00 z&#322;<"+"/div>\n";
ifc += "<"+"div class=\"desc\" data-ellipsis=\"multiline\"><"+"/div>\n";
ifc += "<"+"div class=\"priceDesc\">\n";
ifc += "<"+"span class=\"priceType\">rrp<"+"/span>\n";
ifc += "<"+"del class=\"origPrice\"><"+"/del>\n";
ifc += "<"+"span class=\"price\">405,51 z&#322;<"+"/span>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/a>\n";
ifc += "<"+"/div>\n";
ifc += "\n";
ifc += "<"+"div class=\"cto_product\">\n";
ifc += "<"+"a href=\"http://cat.nl.eu.criteo.com/delivery/ck.php?cppv=1&cpp=823Tr3xFUlIxN0tPbWl6dW9RWkd2bWpKZEIzbWR0Y3c3TW54aUVCMmtXa0d6cWRTSzNHUStSNG9ha1A3RmY2N2Y4R2djZ29idFRuK3lnempmNVhSekU2MHhseS9jdUc0cHB4OHBtVjFJWVZmRjdpdm5HeURSbUN1dnFMU1JzTXMxNm5VUmlHVFk4ZmpFOVhlWEkvWGpKbFlDRzh0UGowaUxINDViTlR5NEdaRGZaTjV1RzlGR1pvOGdCRW1Bb2RkRnJIbzd5a3dGZmRFR3dnUlhlRERhbWxGWGZaWmkvdk8yNjdNbnphS2NjRTRHSGdJaVVvREkwc0Fiay9oQ0JqaUlXS3dPOWtTYVJyeXhYdEhkanc2TzZrOStpL3pnYVM4dXk4QzVybThuSzR5UkhJZz18&maxdest=http%3A%2F%2Fwww.morele.net%2Fmonitor-monitor-lg-55eh5c-s-1001947%2F%3Futm_source%3Dcriteo.com%26utm_medium%3Dbaner%26utm_content%3D300x250%26utm_campaign%3Dremarketing_criteo\" target=\"_blank\" >\n";
ifc += "<"+"div class=\"imgholder\">\n";
ifc += "<"+"img src=\"http://pix.nl.eu.criteo.net/img/img?c=1&cb=1&h=400&i=15285-1001947&m=0&q=80&r=0&u=https%3A%2F%2Fimages.morele.net%2Fi256%2F1001947_0_i256.jpg&w=400&s=KhCT9X92P6tcRk_HLDdmipzE\">\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div class=\"details\">\n";
ifc += "<"+"div class=\"title\" data-ellipsis=\"multiline\">Monitor LG 55EH5C-S Darmowy odbi&#243;r w 19 miastach! Raty od 2064,00 z&#322;<"+"/div>\n";
ifc += "<"+"div class=\"desc\" data-ellipsis=\"multiline\"><"+"/div>\n";
ifc += "<"+"div class=\"priceDesc\">\n";
ifc += "<"+"span class=\"priceType\">rrp<"+"/span>\n";
ifc += "<"+"del class=\"origPrice\"><"+"/del>\n";
ifc += "<"+"span class=\"price\">50.628 z&#322;<"+"/span>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/a>\n";
ifc += "<"+"/div>\n";
ifc += "\n";
ifc += "<"+"div class=\"cto_product\">\n";
ifc += "<"+"a href=\"http://cat.nl.eu.criteo.com/delivery/ck.php?cppv=1&cpp=2VK8O3xFUlIxN0tPbWl6dW9RWkd2bWpKZEIzbWR0Y3c3TW54aUVCMmtXa0d6cWRTSzNHUStSNG9ha1A3RmY2N2Y4R2djZ29idFRuK3lnempmNVhSekU2MHhseS9jdUc0cHB4OHBtVjFJWVZmRjdpdm5HeURSbUN1dnFMU1JzTXMxNm5VUmlHVFk4ZmpFOVhlWEkvWGpKbFlDR3d4ODQxMkZ6eXQwR250ZkJ0Q1lLbEhmRmtwc1p2ekZ5Mm5MU2Y2V3dCME1mWVdOU1hiY0ZJVysvNUQwb2NyOVM3cmFMZjJJMS91dWVjaUcvNkQ1azdUbVZwWC9TbnBoUXpYYXhTeHFHOWJ4NHhYcXlRRW92dnNUand6ZFRvWUpRaDkwMkZFNUlRR2pYSHo4RDFYSERpND18&maxdest=http%3A%2F%2Fwww.morele.net%2Fmorele-sky-g8280-pure-power-774462%2F%3Futm_source%3Dcriteo.com%26utm_medium%3Dbaner%26utm_content%3D300x250%26utm_campaign%3Dremarketing_criteo\" target=\"_blank\" >\n";
ifc += "<"+"div class=\"imgholder\">\n";
ifc += "<"+"img src=\"http://pix.nl.eu.criteo.net/img/img?c=1&cb=1&h=400&i=15285-774462&m=0&q=80&r=0&u=https%3A%2F%2Fimages.morele.net%2Fi256%2F774462_0_i256.jpeg&w=400&s=3-bHHExiXBQCm9BXj8YRt18Q\">\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div class=\"details\">\n";
ifc += "<"+"div class=\"title\" data-ellipsis=\"multiline\">Morele SKY G8280 Pure Power Darmowy odbi&#243;r w 19 miastach! Raty od 338,00 z&#322;<"+"/div>\n";
ifc += "<"+"div class=\"desc\" data-ellipsis=\"multiline\"><"+"/div>\n";
ifc += "<"+"div class=\"priceDesc\">\n";
ifc += "<"+"span class=\"priceType\">rrp<"+"/span>\n";
ifc += "<"+"del class=\"origPrice\"><"+"/del>\n";
ifc += "<"+"span class=\"price\">8.299 z&#322;<"+"/span>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/a>\n";
ifc += "<"+"/div>\n";
ifc += "\n";
ifc += "<"+"div class=\"cto_product\">\n";
ifc += "<"+"a href=\"http://cat.nl.eu.criteo.com/delivery/ck.php?cppv=1&cpp=Rdk6D3xFUlIxN0tPbWl6dW9RWkd2bWpKZEIzbWR0Y3c3TW54aUVCMmtXa0d6cWRTSzNHUStSNG9ha1A3RmY2N2Y4R2djZ29idFRuK3lnempmNVhSekU2MHhseS9jdUc0cHB4OHBtVjFJWVZmRjdpdm5HeURSbUN1dnFMU1JzTXMxNm5VUmlHVFk4ZmpFOVhlWEkvWGpKbFlDR3o3V0N3aHRmd3V1OU1mOThXSlcrc01lV0xiY0ZDUUg4bGVQUHB1OXE4a1NGMFR4andtU1Y4bEY4Z1ltVXF3L2MvS0ZQVDl2cW9rV0JXU010ZzlpUkZ5UGw1L3dQVmcvSXhrV0hCQ1B6Y2YxaTBPYVFhMUlzUzFWUERTRHpDSzB6aXRTS0pKUzVzdk1zQlhKTVJMc0JyND18&maxdest=http%3A%2F%2Fwww.morele.net%2Fkarta-graficzna-karta-graficzna-palit-geforce-gtx-1060-jetstream-6gb-gddr5-192-bit-dvi-hdmi-3xdp-box-ne51060015j9j-998793%2F%3Futm_source%3Dcriteo.com%26utm_medium%3Dbaner%26utm_content%3D300x250%26utm_campaign%3Dremarketing_criteo\" target=\"_blank\" >\n";
ifc += "<"+"div class=\"imgholder\">\n";
ifc += "<"+"img src=\"http://pix.nl.eu.criteo.net/img/img?c=1&cb=1&h=400&i=15285-998793&m=0&q=80&r=0&u=https%3A%2F%2Fimages.morele.net%2Fi256%2F998793_0_i256.jpg&w=400&s=iO99lY5G0qpcrhQ7B7moEcFy\">\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div class=\"details\">\n";
ifc += "<"+"div class=\"title\" data-ellipsis=\"multiline\">Karta graficzna Palit GeForce GTX 1060 JetStream 6GB GDDR5 (192 Bit) DVI, HDMI, 3xDP, BOX (NE51060015J9J) Darmowy odbi&#243;r w 19 miastach! Raty od 55,00 z&#322;<"+"/div>\n";
ifc += "<"+"div class=\"desc\" data-ellipsis=\"multiline\"><"+"/div>\n";
ifc += "<"+"div class=\"priceDesc\">\n";
ifc += "<"+"span class=\"priceType\">rrp<"+"/span>\n";
ifc += "<"+"del class=\"origPrice\"><"+"/del>\n";
ifc += "<"+"span class=\"price\">1.371,45 z&#322;<"+"/span>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/a>\n";
ifc += "<"+"/div>\n";
ifc += "\n";
ifc += "<"+"div class=\"cto_product\">\n";
ifc += "<"+"a href=\"http://cat.nl.eu.criteo.com/delivery/ck.php?cppv=1&cpp=G0dyz3xFUlIxN0tPbWl6dW9RWkd2bWpKZEIzbWR0Y3c3TW54aUVCMmtXa0d6cWRTSzNHUStSNG9ha1A3RmY2N2Y4R2djZ29idFRuK3lnempmNVhSekU2MHhseS9jdUc0cHB4OHBtVjFJWVZmRjdpdm5HeURSbUN1dnFMU1JzTXMxNm5VUmlHVFk4ZmpFOVhlWEkvWGpKbFlDR3o3V0N3aHRmd3V1OU1mOThXSlcrc05kL1lOKzlaLzBnbEE4MjB5cVAyUEtxNmtJOVNSeVVuc0IzN0s3N1gwaFp6ZzBaYlZSV0d1RGJpT3VnVEthd2JITzRkRGczT3oyNmk3RXBSd0Z3VElySmxsVlMvYk1wMDNMa0MxOW1RVHVIWU9hQlF2TEtUSzJ4KzlBUllablNqdz18&maxdest=http%3A%2F%2Fwww.morele.net%2Fkarta-graficzna-karta-graficzna-gigabyte-geforce-gtx-1070-8gb-gddr5-256-bit-hdmi-dvi-d-3x-dp-box-gv-n1070g1-gaming-8gd-774260%2F%3Futm_source%3Dcriteo.com%26utm_medium%3Dbaner%26utm_content%3D300x250%26utm_campaign%3Dremarketing_criteo\" target=\"_blank\" >\n";
ifc += "<"+"div class=\"imgholder\">\n";
ifc += "<"+"img src=\"http://pix.nl.eu.criteo.net/img/img?c=1&cb=1&h=400&i=15285-774260&m=0&q=80&r=0&u=https%3A%2F%2Fimages.morele.net%2Fi256%2F774260_0_i256.png&w=400&s=dcQq--WYR9cUR_AMFreoh92P\">\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div class=\"details\">\n";
ifc += "<"+"div class=\"title\" data-ellipsis=\"multiline\">Karta graficzna Gigabyte GeForce GTX 1070 8GB GDDR5 (256 bit) HDMI, DVI-D, 3x DP, BOX (GV-N1070G1 GAMING-8GD) Szybka dostawa!  Darmowy odbi&#243;r w 19 miastach! Raty od 85,00 z&#322;<"+"/div>\n";
ifc += "<"+"div class=\"desc\" data-ellipsis=\"multiline\"><"+"/div>\n";
ifc += "<"+"div class=\"priceDesc\">\n";
ifc += "<"+"span class=\"priceType\">rrp<"+"/span>\n";
ifc += "<"+"del class=\"origPrice\"><"+"/del>\n";
ifc += "<"+"span class=\"price\">2.089 z&#322;<"+"/span>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/a>\n";
ifc += "<"+"/div>\n";
ifc += "\n";
ifc += "<"+"div class=\"cto_product\">\n";
ifc += "<"+"a href=\"http://cat.nl.eu.criteo.com/delivery/ck.php?cppv=1&cpp=Zo%2B1uXxFUlIxN0tPbWl6dW9RWkd2bWpKZEIzbWR0Y3c3TW54aUVCMmtXa0d6cWRTSzNHUStSNG9ha1A3RmY2N2Y4R2djZ29idFRuK3lnempmNVhSekU2MHhseS9jdUc0cHB4OHBtVjFJWVZmRjdpdm5HeURSbUN1dnFMU1JzTXMxNm5VUmlHVFk4ZmpFOVhlWEkvWGpKbFlDRzlPcmsxRER3dThiaFBJWmRNMWo2V0JJRmY1cVBidVkyUng4UnBoSklPY01HaEdoUlFEdHdWUlQ4KytsQnNEQnloSGdhalF3cStxZkVPcW9YOHhuSUV3OE03YldkZjNrS3lrY0dQMklSdDZBY2IrL2JMWDBOL1FBcXhFWk9YZlBsUXdNV3I2dW56NmZMc3Zwekxoa0huaz18&maxdest=http%3A%2F%2Fwww.morele.net%2Fchlodzenie-cpu-chlodzenie-cpu-thermalright-macho-120-rev-a-tr145-621401%2F%3Futm_source%3Dcriteo.com%26utm_medium%3Dbaner%26utm_content%3D300x250%26utm_campaign%3Dremarketing_criteo\" target=\"_blank\" >\n";
ifc += "<"+"div class=\"imgholder\">\n";
ifc += "<"+"img src=\"http://pix.nl.eu.criteo.net/img/img?c=1&cb=1&h=400&i=15285-621401&m=0&q=80&r=0&u=https%3A%2F%2Fimages.morele.net%2Fi256%2F621401_0_i256.jpg&w=400&s=JD3jWd2zJZU5d0GJoisEKY3L\">\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div class=\"details\">\n";
ifc += "<"+"div class=\"title\" data-ellipsis=\"multiline\">Ch&#322;odzenie CPU Thermalright Macho 120 Rev.A  (TR145) Szybka dostawa!  Darmowy odbi&#243;r w 19 miastach!<"+"/div>\n";
ifc += "<"+"div class=\"desc\" data-ellipsis=\"multiline\"><"+"/div>\n";
ifc += "<"+"div class=\"priceDesc\">\n";
ifc += "<"+"span class=\"priceType\">rrp<"+"/span>\n";
ifc += "<"+"del class=\"origPrice\"><"+"/del>\n";
ifc += "<"+"span class=\"price\">179 z&#322;<"+"/span>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/a>\n";
ifc += "<"+"/div>\n";
ifc += "\n";
ifc += "<"+"div class=\"cto_product\">\n";
ifc += "<"+"a href=\"http://cat.nl.eu.criteo.com/delivery/ck.php?cppv=1&cpp=NcZa%2FnxFUlIxN0tPbWl6dW9RWkd2bWpKZEIzbWR0Y3c3TW54aUVCMmtXa0d6cWRTSzNHUStSNG9ha1A3RmY2N2Y4R2djZ29idFRuK3lnempmNVhSekU2MHhseS9jdUc0cHB4OHBtVjFJWVZmRjdpdm5HeURSbUN1dnFMU1JzTXMxNm5VUmlHVFk4ZmpFOVhlWEkvWGpKbFlDR3o3V0N3aHRmd3V1OU1mOThXSlcrc1Bhb0FsS1EwSVpjd1gyWXJuSHRCWmhMWXV3SnBFZ3NnUklFUXIxdzk1K0xEU0d6ak1TSHlJK0dHOTk5OHpSekJJUHdIYjgrRk1wM1JTNnFFVEhOSjUzck0rMi9pVTBBWlRSZ3Z1VmpoWVpLNGkvNGYyZE1iOTZYWEVCOUJJdURnND18&maxdest=http%3A%2F%2Fwww.morele.net%2Fkarta-graficzna-karta-graficzna-gigabyte-geforce-gtx-1060-6gb-gddr5-gv-n1060g1-gaming-6gd-774555%2F%3Futm_source%3Dcriteo.com%26utm_medium%3Dbaner%26utm_content%3D300x250%26utm_campaign%3Dremarketing_criteo\" target=\"_blank\" >\n";
ifc += "<"+"div class=\"imgholder\">\n";
ifc += "<"+"img src=\"http://pix.nl.eu.criteo.net/img/img?c=1&cb=1&h=400&i=15285-774555&m=0&q=80&r=0&u=https%3A%2F%2Fimages.morele.net%2Fi256%2F774555_2_i256.jpeg&w=400&s=2ay8-OpZf9ZOCYHYbhJI_pB9\">\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div class=\"details\">\n";
ifc += "<"+"div class=\"title\" data-ellipsis=\"multiline\">Karta graficzna Gigabyte GeForce GTX 1060 6GB GDDR5 (GV-N1060G1 GAMING-6GD) Szybka dostawa!  Darmowy odbi&#243;r w 19 miastach! Raty od 58,00 z&#322;<"+"/div>\n";
ifc += "<"+"div class=\"desc\" data-ellipsis=\"multiline\"><"+"/div>\n";
ifc += "<"+"div class=\"priceDesc\">\n";
ifc += "<"+"span class=\"priceType\">rrp<"+"/span>\n";
ifc += "<"+"del class=\"origPrice\"><"+"/del>\n";
ifc += "<"+"span class=\"price\">1.445 z&#322;<"+"/span>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/a>\n";
ifc += "<"+"/div>\n";
ifc += "\n";
ifc += "<"+"div class=\"cto_product\">\n";
ifc += "<"+"a href=\"http://cat.nl.eu.criteo.com/delivery/ck.php?cppv=1&cpp=qIRV4nxFUlIxN0tPbWl6dW9RWkd2bWpKZEIzbWR0Y3c3TW54aUVCMmtXa0d6cWRTSzNHUStSNG9ha1A3RmY2N2Y4R2djZ29idFRuK3lnempmNVhSekU2MHhseS9jdUc0cHB4OHBtVjFJWVZmRjdpdm5HeURSbUN1dnFMU1JzTXMxNm5VUmlHVFk4ZmpFOVhlWEkvWGpKbFlDRzNDTXRjaU83NkpYeWFnaVBMa2x5MTkydm1YVmQzTjhRUkVuRHU2UmFnUnhVYnprY3hOOTJzb1diS0VqZkJET0toZnVHempMYmFqZDJtaTFyMmR0K0JJNzZwOEpacS9PYUowOS9vTFJGbUFlUjdXVFd4RVBpaHp4bHZ6Q29kQTdwVjF0UFo5cWVZTEphRzV5d0labWgwUT18&maxdest=http%3A%2F%2Fwww.morele.net%2Fniszczarka-niszczarka-rexel-auto-500x-2103500eu-716374%2F%3Futm_source%3Dcriteo.com%26utm_medium%3Dbaner%26utm_content%3D300x250%26utm_campaign%3Dremarketing_criteo\" target=\"_blank\" >\n";
ifc += "<"+"div class=\"imgholder\">\n";
ifc += "<"+"img src=\"http://pix.nl.eu.criteo.net/img/img?c=1&cb=1&h=400&i=15285-716374&m=0&q=80&r=0&u=https%3A%2F%2Fimages.morele.net%2Fi256%2F716374_0_i256.jpg&w=400&s=9vJ-4usPiJUtMRdwF1Ftuktq\">\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div class=\"details\">\n";
ifc += "<"+"div class=\"title\" data-ellipsis=\"multiline\">Niszczarka Rexel Auto+500X (2103500EU) Darmowy odbi&#243;r w 19 miastach! Raty od 203,00 z&#322;<"+"/div>\n";
ifc += "<"+"div class=\"desc\" data-ellipsis=\"multiline\"><"+"/div>\n";
ifc += "<"+"div class=\"priceDesc\">\n";
ifc += "<"+"span class=\"priceType\">rrp<"+"/span>\n";
ifc += "<"+"del class=\"origPrice\"><"+"/del>\n";
ifc += "<"+"span class=\"price\">4.995,01 z&#322;<"+"/span>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/a>\n";
ifc += "<"+"/div>\n";
ifc += "\n";
ifc += "<"+"div class=\"cto_product\">\n";
ifc += "<"+"a href=\"http://cat.nl.eu.criteo.com/delivery/ck.php?cppv=1&cpp=YKpvFnxFUlIxN0tPbWl6dW9RWkd2bWpKZEIzbWR0Y3c3TW54aUVCMmtXa0d6cWRTSzNHUStSNG9ha1A3RmY2N2Y4R2djZ29idFRuK3lnempmNVhSekU2MHhseS9jdUc0cHB4OHBtVjFJWVZmRjdpdm5HeURSbUN1dnFMU1JzTXMxNm5VUmlHVFk4ZmpFOVhlWEkvWGpKbFlDR3o3V0N3aHRmd3V1OU1mOThXSlcrc09lUWpwYTdTWWl1SEYzS3hFQnI2NW5aTGluTjM2ZGR4bkVaZktJN0tSSDBXUHlOZWdUSFUxVWdoT1pPVFBnWVFkekhndWhDMnRTL0dybk9mN2pUY1RENE1UOGdqb01xMzNHN0JJWFRQUDgvM2d0NFkxeWdNZTRaUXplS3VjU3c1cz18&maxdest=http%3A%2F%2Fwww.morele.net%2Fkarta-graficzna-karta-graficzna-zotac-geforce-gtx-1060-amp-6gb-gddr5-192-bit-3xdp-hdmi-dvi-box-zt-p10600b-10m-1003488%2F%3Futm_source%3Dcriteo.com%26utm_medium%3Dbaner%26utm_content%3D300x250%26utm_campaign%3Dremarketing_criteo\" target=\"_blank\" >\n";
ifc += "<"+"div class=\"imgholder\">\n";
ifc += "<"+"img src=\"http://pix.nl.eu.criteo.net/img/img?c=1&cb=1&h=400&i=15285-1003488&m=0&q=80&r=0&u=https%3A%2F%2Fimages.morele.net%2Fi256%2F1003488_0_i256.jpg&w=400&s=y0_Hd3yfhojPOgPm42tzaqYa\">\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div class=\"details\">\n";
ifc += "<"+"div class=\"title\" data-ellipsis=\"multiline\">Karta graficzna Zotac GeForce GTX 1060 AMP! 6GB GDDR5 (192 Bit) 3xDP, HDMI, DVI. BOX (ZT-P10600B-10M) Darmowy odbi&#243;r w 19 miastach! Raty od 53,00 z&#322;<"+"/div>\n";
ifc += "<"+"div class=\"desc\" data-ellipsis=\"multiline\"><"+"/div>\n";
ifc += "<"+"div class=\"priceDesc\">\n";
ifc += "<"+"span class=\"priceType\">rrp<"+"/span>\n";
ifc += "<"+"del class=\"origPrice\"><"+"/del>\n";
ifc += "<"+"span class=\"price\">1.319,92 z&#322;<"+"/span>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/a>\n";
ifc += "<"+"/div>\n";
ifc += "\n";
ifc += "<"+"/div>\n";
ifc += "<"+"!-- PRIVACY[BOTTOM:RIGHT] -->\n";
ifc += " <"+"div class=\"footer\" id=\"footer\"> \n";
ifc += "                            <"+"div class=\'privacy\'>\n";
ifc += "                                <"+"a href=\'http://info.criteo.com/pac/privacy/informations?infonorm=3&amp;partner=15285&amp;campaignid=61975&amp;zoneid=363342&amp;bannerid=3174075&amp;displayid=cfed3edd74\' target=\'_blank\'><"+"/a>\n";
ifc += "                            <"+"/div> <"+"a href=\"http://cat.nl.eu.criteo.com/delivery/ck.php?cppv=1&amp;cpp=h6YC53xFUlIxN0tPbWl6dW9RWkd2bWpKZEIzbWR0Y3c3TW54aUVCMmtXa0d6cWRTSzNHUStSNG9ha1A3RmY2N2Y4R2djZ29idFRuK3lnempmNVhSekU2MHhseS9jdUc0cHB4OHBtVjFJWVZmRjdpdm5HeURSbUN1dnFMU1JzTXMxNm5VUmlHVFk4ZmpFOVhlWEkvWGpKbFlDRzh0UGowaUxINDViTlR5NEdaRGZaTjY1WE5zYjJWZDdteWR5alQybDNTYURNK05FblRUSzkyUjVvcWVxblV6c00rT3BmNnZDYXNpWVR4b2tubVR6SDRtTUE2dFl5emlwSFRUeUNRTjJmVlZOVExOSTZaMGxsSm1NVEhUY2JhendKUT09fA%3D%3D&amp;maxdest=http%3A%2F%2Fwww.morele.net%3Futm_source%3Dcriteo.com%26utm_medium%3Dbaner%26utm_content%3D300x250%26utm_campaign%3Dremarketing_criteo\" target=\"_blank\" id=\"adUrl\" class=\"adUrl\" >Advertisement | morele.net<"+"/a> <"+"span id=\"legal\" class=\"legal\" onmouseover=\"javascript:display_hide(\'legalover\');\"><"+"/span> <"+"/div> <"+"div id=\"legalover\" class=\"legalover\" onmouseout=\"javascript:display_hide(\'legalover\');\"><"+"/div>\n";
ifc += " <"+"/div>\n";
ifc += "<"+"style>#cto_banner_content .privacy {\n";
ifc += "                    width:77px;\n";
ifc += "                    float:right;\n";
ifc += "                    text-align:right;\n";
ifc += "                }\n";
ifc += "\n";
ifc += "                #cto_banner_content .privacy a {\n";
ifc += "                    display:inline-block;\n";
ifc += "                    width:19px;\n";
ifc += "                    height:15px;\n";
ifc += "                    background-image:url(http://static.eu.criteo.net/flash/icon/nai_small.png);\n";
ifc += "                }\n";
ifc += "\n";
ifc += "                #cto_banner_content .privacy a:hover {\n";
ifc += "                    width:77px;\n";
ifc += "                    height:15px;\n";
ifc += "                    background-image:url(http://static.eu.criteo.net/flash/icon/nai_big.png);\n";
ifc += "                }<"+"/style>\n";
ifc += "<"+"script type=\'text/javascript\'>(function() { var arrayEquals = function (a, b) {\n";
ifc += "                if(a.length != b.length) return false;\n";
ifc += "                a = a.sort();\n";
ifc += "                b = b.sort();\n";
ifc += "                for(var i = 0; i <"+" a.length; ++i) {\n";
ifc += "                    if (a[i] != b[i]) return false;\n";
ifc += "                }\n";
ifc += "                return true;\n";
ifc += "            };\n";
ifc += "\n";
ifc += "            var arrayIterate = function (a, fct) {\n";
ifc += "                var len = a.length;\n";
ifc += "                for(var i = 0; i <"+" len; ++i) {\n";
ifc += "                    fct(a[i], i); \n";
ifc += "                }\n";
ifc += "             };\n";
ifc += "   \n";
ifc += "            var arrayWhere = function (a, fct) {\n";
ifc += "                b = [];\n";
ifc += "                arrayIterate(a, function(elt, index) {\n";
ifc += "                    if(fct(elt, index)) b.push(elt);\n";
ifc += "                });\n";
ifc += "                return b;\n";
ifc += "             };\n";
ifc += "      \n";
ifc += "            var arrayMap = function (a, fct) {\n";
ifc += "                b = [];\n";
ifc += "                arrayIterate(a, function(elt, index) {\n";
ifc += "                    b[index] = fct(elt, index);\n";
ifc += "                });\n";
ifc += "                return b;\n";
ifc += "            };\n";
ifc += "\n";
ifc += "            var multilineEllipsis = function (div) {\n";
ifc += "                var t = div.textContent || div.innerText;\n";
ifc += "                var d = document.createElement(\'div\');\n";
ifc += "                var i = 0;    \n";
ifc += "                d.style.width = div.offsetWidth + \'px\';\n";
ifc += "                d.style.visibility = \"hidden\";\n";
ifc += "                div.appendChild(d);\n";
ifc += "\n";
ifc += "                while(d.offsetHeight <"+"= div.offsetHeight && i <"+" t.length) {\n";
ifc += "                    d.textContent = d.innerText = t.substr(0, i) + \'...\';\n";
ifc += "                    ++i;\n";
ifc += "                }\n";
ifc += "\n";
ifc += "                div.removeChild(d);\n";
ifc += "                if(i != t.length) div.textContent = div.innerText = t.substr(0, i-2) + \'...\';\n";
ifc += "            };\n";
ifc += "\n";
ifc += "            (function() {\n";
ifc += "                var c = document.getElementById(\'cto_banner_content\');\n";
ifc += "                var isMultilineEllipsis = function(elt) { return elt.getAttribute(\'data-ellipsis\') == \'multiline\'; };\n";
ifc += "                arrayIterate(arrayWhere(c.getElementsByTagName(\'*\'), isMultilineEllipsis), multilineEllipsis);\n";
ifc += "            })(); })();<"+"/script>\n";
ifc += "<"+"script type=\"text/javascript\">\n";
ifc += "var legal = document.getElementById(\"legal\");\n";
ifc += "if(legal.innerText == \"\"){legal.style.display=\"none\";}\n";
ifc += "else {document.getElementById(\"adUrl\").style.maxWidth=\"65px\";} function display_hide(id) { var legalLength = legal.innerHTML.length; var element = document.getElementById(id); if(element===null) return false; if((element.style.visibility==\"hidden\") && (legalLength > 10)){ element.style.visibility=\"visible\"; } else { element.style.visibility=\"hidden\"; } return true;\n";
ifc += "} (function() { var getElts = function(className, domElem) { var desc = []; if (document.getElementsByClassName) { desc = domElem.getElementsByClassName(className); } else { var elem = domElem.getElementsByTagName(\'*\'); for (var x = 0; x <"+" elem.length; x++) { if ((\' \' + elem[x].className + \' \').indexOf(\' \' + className + \' \') > -1) desc.push(elem[x]); } } return desc; }; var truncate = function(div, maxCharacter) { var t = div.textContent || div.innerText || \"\"; var trimmed = t.replace(\'\\\\n\', \'\').replace(/^ +| +$/g, \'\'); if(trimmed.length > maxCharacter) div.textContent = div.innerText = trimmed.substr(0, maxCharacter-3) + \'...\'; }; var products = getElts(\"cto_product\", document); for(var x = 0; x <"+" products.length; ++x) { var price = getElts(\"priceDesc\", products[x])[0]; var priceType = getElts(\"priceType\", price)[0]; var priceNumber = getElts(\"price\", price)[0]; var priceOrig = getElts(\"origPrice\", price)[0]; var priceTypeText = priceType.textContent || priceType.innerText || \"\"; if (priceNumber.innerHTML == \"\" || priceNumber.innerHTML.length > 14) { price.removeChild(priceOrig); price.removeChild(priceType); price.removeChild(priceNumber); } else if (priceTypeText.indexOf(\"__\") == 0) { var altprice = priceTypeText.replace(/_/g, \"\"); priceType.innerHTML = altprice; price.removeChild(priceOrig); } else if (priceTypeText == \"rrp\") { price.removeChild(priceType); } }\n";
ifc += "})(); <"+"/script><"+"/div><"+"div style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'>\n";
ifc += "<"+"iframe id=\'ifcfed3edd74\' name=\'ifcfed3edd74\' width=\'1px\' height=\'1px\'><"+"/iframe>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div id=\'beacon_cfed3edd74\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'>\n";
ifc += "<"+"img width=\"0\" height=\"0\" src=\"http://cat.nl.eu.criteo.com/delivery/lg.php?cppv=1&cpp=rVf6TnxFUlIxN0tPbWl6dW9RWkd2bWpKZEIzbWR0Y3c3TW54aUVCMmtXa0d6cWRTSzNHUStSNG9ha1A3RmY2N2Y4R2djZ29idFRuK3lnempmNVhSekU2MHhseS9jdUc0cHB4OHBtVjFJWVZmRjdpdm5HeURSbUN1dnFMU1JzTXMxNm5VUkJsTk5weU5EdmU0ZWsxdHpvL3QyQmd0MTJBRGJ3SERDZTYzUXJvUkR6clBOUjhJWUhYb011dXRRTWxoR1c2QTJFNzYxdVZzbFhiNEZCOTZTTmszQXpCaGxzeEE3VUltN3lUbmM2UVpBZjNabnRpdWhKRXd0WUJmYXIrNG1WcHJya2NvQWh5Vy9RM3dkS01xZVZtOG14TWRGQ2cveWswOTEzTVNjNHhadnFnaz18\"/>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/body>\n";
ifc += "<"+"/html>\n";

var fillIframe = function(ifrd) {
    var getDocument = function(iframe) {
        var result_document = iframe.contentWindow || iframe.contentDocument;
        if (result_document && result_document.document)
            result_document = result_document.document;
        return result_document;
    };
    var c = getDocument(ifrd);
    if (c) {
        c.open();
        c.write(ifc);
        c.close();
    }
};


var maxRetryAttempts = 100;
var loaded = false;
var pollIframe = function() {
    var ifrd = document.getElementById('cto_iframe_cfed3edd74');
    if (ifrd && isIE) {
         ifrd.onload = function() {
            if(!loaded) {
                loaded = true;
                fillIframe(ifrd);
            }
        };
    } else if (ifrd) {
        loaded = true;
        fillIframe(ifrd);
    } else if (maxRetryAttempts-- > 0) {
        setTimeout(pollIframe, 10);
    }
};pollIframe();
})();
