(function(){
var isIE = window.navigator.userAgent.indexOf("MSIE ") > 0;
var ifr = "<"+"iframe id=\"cto_iframe_0802fd96a4\" frameBorder=\"0\" allowtransparency=\"true\" hspace=\"0\" marginwidth=\"0\" marginheight=\"0\" scrolling=\"no\" vspace=\"0\" width=\"300px\" height=\"250px\"\n";
if(isIE && document.domain !== window.location.hostname) {
ifr += " src=\"javascript:'<script>window.onload=function(){document.write(\\\'<script>document.domain = &quot;"+document.domain + "&quot;;<\\\\/script>\\\');document.close();};</script>'\"";
}
ifr += "><"+"/iframe>\n";
document.write(ifr);
var ifc = "\n";
ifc += "<"+"!DOCTYPE html>\n";
ifc += "<"+"html>\n";
ifc += "  <"+"head>\n";
ifc += "    <"+"meta name=\"format-detection\" content=\"telephone=no\"><"+"meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\n";
ifc += "  <"+"/head>\n";
ifc += "  <"+"body><"+"div id=\'cto_banner_content\'><"+"style>\n";
ifc += "#cto_products .cto_product .imgholder{ text-align : center; background : #ffffff; float : left; margin-right : 7px; width : 113px; height : 113px;\n";
ifc += "} #cto_products .cto_product .imgholder img{ border : none; max-width : 113px; max-height : 113px; *width : expression(this.width >= this.height ? \"113px\" : \"auto\"); *height : expression(this.width <"+" this.height ? \"113px\" : \"auto\");\n";
ifc += "} #cto_products .cto_product .title{ overflow : hidden; color : #016090; font-size : 13px; height : 36px; line-height : 15px; font-weight : bold;\n";
ifc += "} #cto_products .cto_product a:hover .title{ text-decoration : underline;\n";
ifc += "} #cto_products .cto_product .desc{ overflow : hidden; color : #646464; font-size : 11px; height : 48px; line-height : 13px;\n";
ifc += "} #cto_products .cto_product .priceDesc{ color : #016090; font-size : 12px; height : 31px; line-height : 14px;\n";
ifc += "} #cto_products .cto_product .details{ float : left; width : 176px;\n";
ifc += "} #cto_bannerContent{ width : 298px; height : 248px; background : #ffffff; position : relative; font-family : Arial,sans-serif; font-size : 0; overflow : hidden; border : 1px solid #e8e8e8;\n";
ifc += "} #cto_products{ height : 231px; width : 298px; overflow : hidden;\n";
ifc += "} #cto_products .cto_product{ width : 296px; height : 113px; float : left; text-align : left; overflow : hidden; vertical-align : top; zoom : 1; position : relative; *zoom : 1; *display : inline; margin : 1px 1px 1px 1px;\n";
ifc += "} #cto_bannerContent .footer{ height : 17px; line-height : 16px; position : relative; text-align : left;\n";
ifc += "} #cto_products .cto_product * { *cursor:pointer;\n";
ifc += "} #cto_products .cto_product a { color: black; text-decoration:none;\n";
ifc += "} #cto_bannerContent .adUrl { font-size: 11px; line-height: 13px; color: #808080; text-decoration: none; cursor: pointer; *cursor:pointer; display: inline-block; *display: inline; zoom: 1; margin-left: 4px; vertical-align: top; position: absolute; left: 0;\n";
ifc += "} #cto_bannerContent .adUrl:hover { text-decoration: underline;\n";
ifc += "}\n";
ifc += "<"+"/style>\n";
ifc += "<"+"div id=\"cto_bannerContent\">\n";
ifc += "<"+"div id=\"cto_products\">\n";
ifc += "\n";
ifc += "<"+"div class=\"cto_product\">\n";
ifc += "<"+"a href=\"http://cat.nl.eu.criteo.com/delivery/ck.php?cppv=1&cpp=fnICx3xQVWQyN0NISHNTdy9SbCs3VzIzVGJEMjVKMUZjUFRwSXNTVVRCVHM2UzFxdXR2VmROSXAyUXJtV01ZN1hsUk9pMEZDOG9PZWw2YkZ6RlFlZjNuTVk3MFhoV292SmNTbnVhRUU3Z1NEc1U4ZlhYVXNjZW5EYmRVYjFMWEhZMlRYUW1OWnZXam1SUGhlN2NvK3VvTytmRHJ1TmJ4blBrVzNvWGkzeEZFQzlLUFcva2t6Z1lma3daUU51VHhTTzkwbm5GbDlFMlBFL2pWRW56SWZldjlIU3JuYjN4K1lkNWpyTG5pMUZhV1ZIY2pmbmhRZ0RTdkp5djN5YnhZOXlaNzZ3RHBsdnozK3NQNFRsblR3Wnc5Y0l6QitBRHNHQjl5bDVCMXhqRTRQK1FkRT18&maxdest=http%3A%2F%2Fwww.morele.net%2Fmonitor-monitor-lg-55eh5c-s-1001947%2F%3Futm_source%3Dcriteo.com%26utm_medium%3Dbaner%26utm_content%3D300x250%26utm_campaign%3Dremarketing_criteo\" target=\"_blank\" >\n";
ifc += "<"+"div class=\"imgholder\">\n";
ifc += "<"+"img src=\"http://pix.nl.eu.criteo.net/img/img?c=1&cb=1&h=400&i=15285-1001947&m=0&q=80&r=0&u=https%3A%2F%2Fimages.morele.net%2Fi256%2F1001947_0_i256.jpg&w=400&s=KhCT9X92P6tcRk_HLDdmipzE\">\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div class=\"details\">\n";
ifc += "<"+"div class=\"title\" data-ellipsis=\"multiline\">Monitor LG 55EH5C-S Darmowy odbi&#243;r w 19 miastach! Raty od 2064,00 z&#322;<"+"/div>\n";
ifc += "<"+"div class=\"desc\" data-ellipsis=\"multiline\"><"+"/div>\n";
ifc += "<"+"div class=\"priceDesc\">\n";
ifc += "<"+"span class=\"priceType\">rrp<"+"/span>\n";
ifc += "<"+"del class=\"origPrice\"><"+"/del>\n";
ifc += "<"+"span class=\"price\">50.628 z&#322;<"+"/span>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/a>\n";
ifc += "<"+"/div>\n";
ifc += "\n";
ifc += "<"+"div class=\"cto_product\">\n";
ifc += "<"+"a href=\"http://cat.nl.eu.criteo.com/delivery/ck.php?cppv=1&cpp=Vjavg3xQVWQyN0NISHNTdy9SbCs3VzIzVGJEMjVKMUZjUFRwSXNTVVRCVHM2UzFxdXR2VmROSXAyUXJtV01ZN1hsUk9pMEZDOG9PZWw2YkZ6RlFlZjNuTVk3MFhoV292SmNTbnVhRUU3Z1NEc1U4ZlhYVXNjZW5EYmRVYjFMWEhZMlRYUW1OWnZXam1SUGhlN2NvK3VvTytmRHNQbGgzSHUraE5wc1dQcmZML3Q4djE5dXFTbHhZR1AyZlRQUnhsZDFjc3NjOHlQN2hJb0JtK3ZGVitZV0ZRRWVEcm1PMFRrYSthNEhBeExJME9rY1dLMFhBZnhrYXRuYjAvTGdZUmZZS1I1UmVQTnVrWmhpYU1YQ3l2Tnp0a2VNWGVkNGEvRFdsdWU0Nm5VN1ZiTk1hbz18&maxdest=http%3A%2F%2Fwww.morele.net%2Fmorele-sky-g8280-pure-power-774462%2F%3Futm_source%3Dcriteo.com%26utm_medium%3Dbaner%26utm_content%3D300x250%26utm_campaign%3Dremarketing_criteo\" target=\"_blank\" >\n";
ifc += "<"+"div class=\"imgholder\">\n";
ifc += "<"+"img src=\"http://pix.nl.eu.criteo.net/img/img?c=1&cb=1&h=400&i=15285-774462&m=0&q=80&r=0&u=https%3A%2F%2Fimages.morele.net%2Fi256%2F774462_0_i256.jpeg&w=400&s=3-bHHExiXBQCm9BXj8YRt18Q\">\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div class=\"details\">\n";
ifc += "<"+"div class=\"title\" data-ellipsis=\"multiline\">Morele SKY G8280 Pure Power Darmowy odbi&#243;r w 19 miastach! Raty od 338,00 z&#322;<"+"/div>\n";
ifc += "<"+"div class=\"desc\" data-ellipsis=\"multiline\"><"+"/div>\n";
ifc += "<"+"div class=\"priceDesc\">\n";
ifc += "<"+"span class=\"priceType\">rrp<"+"/span>\n";
ifc += "<"+"del class=\"origPrice\"><"+"/del>\n";
ifc += "<"+"span class=\"price\">8.299 z&#322;<"+"/span>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/a>\n";
ifc += "<"+"/div>\n";
ifc += "\n";
ifc += "<"+"div class=\"cto_product\">\n";
ifc += "<"+"a href=\"http://cat.nl.eu.criteo.com/delivery/ck.php?cppv=1&cpp=Y5je5HxQVWQyN0NISHNTdy9SbCs3VzIzVGJEMjVKMUZjUFRwSXNTVVRCVHM2UzFxdXR2VmROSXAyUXJtV01ZN1hsUk9pMEZDOG9PZWw2YkZ6RlFlZjNuTVk3MFhoV292SmNTbnVhRUU3Z1NEc1U4ZlhYVXNjZW5EYmRVYjFMWEhZMlRYUW1OWnZXam1SUGhlN2NvK3VvTytmRG8vTHUxRnQ4cGNCTVo3Qk5BV0lQMnRDQ2NnbXQzZGNWbG1QbEhUUSt4YUpUTGIycVBBOUUrZTlCZE1EbmJ2YjJobEdpVnErblNhbERqSWkwRHFoSzk3dStPaVVuVVJZNFB5dVg4TlpPYXhIRitWbkNIZ2tiTWx2VFNKZkxuZGtqM1NPc3YrQjkrTkFMN1d0TWZ1OGRvMD18&maxdest=http%3A%2F%2Fwww.morele.net%2Fdysk-ssd-dysk-ssd-samsung-850-evo-250gb-sata3-mz-75e250b-eu-701416%2F%3Futm_source%3Dcriteo.com%26utm_medium%3Dbaner%26utm_content%3D300x250%26utm_campaign%3Dremarketing_criteo\" target=\"_blank\" >\n";
ifc += "<"+"div class=\"imgholder\">\n";
ifc += "<"+"img src=\"http://pix.nl.eu.criteo.net/img/img?c=1&cb=1&h=400&i=15285-701416&m=0&q=80&r=0&u=https%3A%2F%2Fimages.morele.net%2Fi256%2F701416_0_i256.jpg&w=400&s=niXri3zE7Ifwz5qRZJH0a8n1\">\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div class=\"details\">\n";
ifc += "<"+"div class=\"title\" data-ellipsis=\"multiline\">Dysk SSD Samsung 850 EVO 250GB SATA3 (MZ-75E250B/EU) Szybka dostawa! od r&#281;ki w Warszawie  Darmowy odbi&#243;r w 19 miastach! Raty od 16,00 z&#322;<"+"/div>\n";
ifc += "<"+"div class=\"desc\" data-ellipsis=\"multiline\"><"+"/div>\n";
ifc += "<"+"div class=\"priceDesc\">\n";
ifc += "<"+"span class=\"priceType\">rrp<"+"/span>\n";
ifc += "<"+"del class=\"origPrice\"><"+"/del>\n";
ifc += "<"+"span class=\"price\">399 z&#322;<"+"/span>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/a>\n";
ifc += "<"+"/div>\n";
ifc += "\n";
ifc += "<"+"div class=\"cto_product\">\n";
ifc += "<"+"a href=\"http://cat.nl.eu.criteo.com/delivery/ck.php?cppv=1&cpp=aQmlMHxQVWQyN0NISHNTdy9SbCs3VzIzVGJEMjVKMUZjUFRwSXNTVVRCVHM2UzFxdXR2VmROSXAyUXJtV01ZN1hsUk9pMEZDOG9PZWw2YkZ6RlFlZjNuTVk3MFhoV292SmNTbnVhRUU3Z1NEc1U4ZlhYVXNjZW5EYmRVYjFMWEhZMlRYUW1OWnZXam1SUGhlN2NvK3VvTytmRG8vTHUxRnQ4cGNCTVo3Qk5BV0lQMnZaY2NtMnQzemE4R1lWQjJKU25rczgrVDVaSkdrckZwNmVBeEJDQkFaazFkM3NJZTU5Q1FUV1hUb0pYWkNOTHg5d3RUU0xJU214T3NZWE1xRTQyOVZ5a1RkWVJubDQ2Q0Fmbk1sLzgveExXQi9xQjlhYjZRMlZ6V0ZVM1I4RnZCUT18&maxdest=http%3A%2F%2Fwww.morele.net%2Fdysk-ssd-dysk-ssd-crucial-mx200-250gb-sata3-ct250mx200ssd6-712714%2F%3Futm_source%3Dcriteo.com%26utm_medium%3Dbaner%26utm_content%3D300x250%26utm_campaign%3Dremarketing_criteo\" target=\"_blank\" >\n";
ifc += "<"+"div class=\"imgholder\">\n";
ifc += "<"+"img src=\"http://pix.nl.eu.criteo.net/img/img?c=1&cb=1&h=400&i=15285-712714&m=0&q=80&r=0&u=https%3A%2F%2Fimages.morele.net%2Fi256%2F712714_0_i256.jpg&w=400&s=nAJ6-umSLmA77ZYUCniH2dVq\">\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div class=\"details\">\n";
ifc += "<"+"div class=\"title\" data-ellipsis=\"multiline\">Dysk SSD Crucial MX200 250GB SATA3 (CT250MX200SSD6) Darmowy odbi&#243;r w 19 miastach! Raty od 16,00 z&#322;<"+"/div>\n";
ifc += "<"+"div class=\"desc\" data-ellipsis=\"multiline\"><"+"/div>\n";
ifc += "<"+"div class=\"priceDesc\">\n";
ifc += "<"+"span class=\"priceType\">rrp<"+"/span>\n";
ifc += "<"+"del class=\"origPrice\"><"+"/del>\n";
ifc += "<"+"span class=\"price\">405,51 z&#322;<"+"/span>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/a>\n";
ifc += "<"+"/div>\n";
ifc += "\n";
ifc += "<"+"div class=\"cto_product\">\n";
ifc += "<"+"a href=\"http://cat.nl.eu.criteo.com/delivery/ck.php?cppv=1&cpp=jY%2BlcnxQVWQyN0NISHNTdy9SbCs3VzIzVGJEMjVKMUZjUFRwSXNTVVRCVHM2UzFxdXR2VmROSXAyUXJtV01ZN1hsUk9pMEZDOG9PZWw2YkZ6RlFlZjNuTVk3MFhoV292SmNTbnVhRUU3Z1NEc1U4ZlhYVXNjZW5EYmRVYjFMWEhZMlRYUW1OWnZXam1SUGhlN2NvK3VvTytmRHJEWklHbTloQW1EaGZIbENneXBwdmZhRUlnZ1B4VWNldmxxRzFFeEhHSlJ6c2RkWVZ4aFpWbGhzeHdIMWpZTkppRzBQQVo0a3ExSzlqUS9JY3hBQ1JDYXE0V1JmWVQrVnZHSk1kLzRnMHN1Z0E5K0RVdzNuYUpCRy9RS0NGaG9uaEdTN3pBR2xMd054UWtzSE5YTG91az18&maxdest=http%3A%2F%2Fwww.morele.net%2Fchlodzenie-cpu-chlodzenie-cpu-thermalright-macho-120-rev-a-tr145-621401%2F%3Futm_source%3Dcriteo.com%26utm_medium%3Dbaner%26utm_content%3D300x250%26utm_campaign%3Dremarketing_criteo\" target=\"_blank\" >\n";
ifc += "<"+"div class=\"imgholder\">\n";
ifc += "<"+"img src=\"http://pix.nl.eu.criteo.net/img/img?c=1&cb=1&h=400&i=15285-621401&m=0&q=80&r=0&u=https%3A%2F%2Fimages.morele.net%2Fi256%2F621401_0_i256.jpg&w=400&s=JD3jWd2zJZU5d0GJoisEKY3L\">\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div class=\"details\">\n";
ifc += "<"+"div class=\"title\" data-ellipsis=\"multiline\">Ch&#322;odzenie CPU Thermalright Macho 120 Rev.A  (TR145) Szybka dostawa!  Darmowy odbi&#243;r w 19 miastach!<"+"/div>\n";
ifc += "<"+"div class=\"desc\" data-ellipsis=\"multiline\"><"+"/div>\n";
ifc += "<"+"div class=\"priceDesc\">\n";
ifc += "<"+"span class=\"priceType\">rrp<"+"/span>\n";
ifc += "<"+"del class=\"origPrice\"><"+"/del>\n";
ifc += "<"+"span class=\"price\">179 z&#322;<"+"/span>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/a>\n";
ifc += "<"+"/div>\n";
ifc += "\n";
ifc += "<"+"div class=\"cto_product\">\n";
ifc += "<"+"a href=\"http://cat.nl.eu.criteo.com/delivery/ck.php?cppv=1&cpp=aZhPMHxQVWQyN0NISHNTdy9SbCs3VzIzVGJEMjVKMUZjUFRwSXNTVVRCVHM2UzFxdXR2VmROSXAyUXJtV01ZN1hsUk9pMEZDOG9PZWw2YkZ6RlFlZjNuTVk3MFhoV292SmNTbnVhRUU3Z1NEc1U4ZlhYVXNjZW5EYmRVYjFMWEhZMlRYUW1OWnZXam1SUGhlN2NvK3VvTytmRHJxNm5ZY21YVTZiMHQ0YUtlbHNybkNCQUpBeFBKa1BtYXB3UTQycC8zQTdjU01MM0lYZjB4N3FpM0hPak9iWGhaSGQybGh0Wk5LYUM2bmtXaWRKVWkvZUdwZ092QTF5Z0hZdWRjbXFVakZ3dmxhQU5jWVF1YlAxTFhPQmd2UEFwamlQczNMaDc1T2VXRUQybTg1aHdyMD18&maxdest=http%3A%2F%2Fwww.morele.net%2Fkarta-graficzna-karta-graficzna-palit-geforce-gtx-1060-jetstream-6gb-gddr5-192-bit-dvi-hdmi-3xdp-box-ne51060015j9j-998793%2F%3Futm_source%3Dcriteo.com%26utm_medium%3Dbaner%26utm_content%3D300x250%26utm_campaign%3Dremarketing_criteo\" target=\"_blank\" >\n";
ifc += "<"+"div class=\"imgholder\">\n";
ifc += "<"+"img src=\"http://pix.nl.eu.criteo.net/img/img?c=1&cb=1&h=400&i=15285-998793&m=0&q=80&r=0&u=https%3A%2F%2Fimages.morele.net%2Fi256%2F998793_0_i256.jpg&w=400&s=iO99lY5G0qpcrhQ7B7moEcFy\">\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div class=\"details\">\n";
ifc += "<"+"div class=\"title\" data-ellipsis=\"multiline\">Karta graficzna Palit GeForce GTX 1060 JetStream 6GB GDDR5 (192 Bit) DVI, HDMI, 3xDP, BOX (NE51060015J9J) Darmowy odbi&#243;r w 19 miastach! Raty od 55,00 z&#322;<"+"/div>\n";
ifc += "<"+"div class=\"desc\" data-ellipsis=\"multiline\"><"+"/div>\n";
ifc += "<"+"div class=\"priceDesc\">\n";
ifc += "<"+"span class=\"priceType\">rrp<"+"/span>\n";
ifc += "<"+"del class=\"origPrice\"><"+"/del>\n";
ifc += "<"+"span class=\"price\">1.371,45 z&#322;<"+"/span>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/a>\n";
ifc += "<"+"/div>\n";
ifc += "\n";
ifc += "<"+"div class=\"cto_product\">\n";
ifc += "<"+"a href=\"http://cat.nl.eu.criteo.com/delivery/ck.php?cppv=1&cpp=PPud63xQVWQyN0NISHNTdy9SbCs3VzIzVGJEMjVKMUZjUFRwSXNTVVRCVHM2UzFxdXR2VmROSXAyUXJtV01ZN1hsUk9pMEZDOG9PZWw2YkZ6RlFlZjNuTVk3MFhoV292SmNTbnVhRUU3Z1NEc1U4ZlhYVXNjZW5EYmRVYjFMWEhZMlRYUW1OWnZXam1SUGhlN2NvK3VvTytmRHJxNm5ZY21YVTZiMHQ0YUtlbHNybkJaUU1CODQwOHVxTS9uVTFvWFpxSjUyc0tRWnBFSmc4RVFoNWlaZkNDcmtFQWVteUdINEE1T1hvSmdrc2lwWkkxV2l4bEpjY1h3MG1QUG8vK0RyMGJ5VHBVQzRHYkhVakV6UElNeEhDVm1MRHN1d29pbjN0cjYzVW5yZEpGall3OD18&maxdest=http%3A%2F%2Fwww.morele.net%2Fbitfenix-spectre-pro-bff-wpro-14025w-rp-552887%2F%3Futm_source%3Dcriteo.com%26utm_medium%3Dbaner%26utm_content%3D300x250%26utm_campaign%3Dremarketing_criteo\" target=\"_blank\" >\n";
ifc += "<"+"div class=\"imgholder\">\n";
ifc += "<"+"img src=\"http://pix.nl.eu.criteo.net/img/img?c=1&cb=1&h=400&i=15285-552887&m=0&q=80&r=0&u=https%3A%2F%2Fimages.morele.net%2Fb128%2F552887_1387639.jpg&w=400&s=TuhjRWQsmznZd4FLbuhpO3RJ\">\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div class=\"details\">\n";
ifc += "<"+"div class=\"title\" data-ellipsis=\"multiline\">BitFenix Spectre Pro  (BFF-WPRO-14025W-RP) Darmowy odbi&#243;r w 19 miastach!<"+"/div>\n";
ifc += "<"+"div class=\"desc\" data-ellipsis=\"multiline\"><"+"/div>\n";
ifc += "<"+"div class=\"priceDesc\">\n";
ifc += "<"+"span class=\"priceType\">rrp<"+"/span>\n";
ifc += "<"+"del class=\"origPrice\"><"+"/del>\n";
ifc += "<"+"span class=\"price\">55,54 z&#322;<"+"/span>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/a>\n";
ifc += "<"+"/div>\n";
ifc += "\n";
ifc += "<"+"div class=\"cto_product\">\n";
ifc += "<"+"a href=\"http://cat.nl.eu.criteo.com/delivery/ck.php?cppv=1&cpp=Rd8J9XxQVWQyN0NISHNTdy9SbCs3VzIzVGJEMjVKMUZjUFRwSXNTVVRCVHM2UzFxdXR2VmROSXAyUXJtV01ZN1hsUk9pMEZDOG9PZWw2YkZ6RlFlZjNuTVk3MFhoV292SmNTbnVhRUU3Z1NEc1U4ZlhYVXNjZW5EYmRVYjFMWEhZMlRYUW1OWnZXam1SUGhlN2NvK3VvTytmRG8vTHUxRnQ4cGNCTVo3Qk5BV0lQMnVKYjJhSHZCc3ZXT09jd2k3NGFaOEtFclgxY2ZWZmdnMGswUGpKTXlVd24za3lMMGJOM3FVN3RCaktTdmMyN0tTSW5RUys0U08yc0hNS09BelV0QXR0Yk5idFpTWXhIaTNycElXTEVweTdsR2RiSEV5Y2RQT0dlM2drUlJuZ0lCaz18&maxdest=http%3A%2F%2Fwww.morele.net%2Fdysk-ssd-dysk-ssd-crucial-mx200-500gb-sata3-ct500mx200ssd6-720727%2F%3Futm_source%3Dcriteo.com%26utm_medium%3Dbaner%26utm_content%3D300x250%26utm_campaign%3Dremarketing_criteo\" target=\"_blank\" >\n";
ifc += "<"+"div class=\"imgholder\">\n";
ifc += "<"+"img src=\"http://pix.nl.eu.criteo.net/img/img?c=1&cb=1&h=400&i=15285-720727&m=0&q=80&r=0&u=https%3A%2F%2Fimages.morele.net%2Fi256%2F720727_0_i256.jpeg&w=400&s=qaxZyVH3PyyzULue42TqV-19\">\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div class=\"details\">\n";
ifc += "<"+"div class=\"title\" data-ellipsis=\"multiline\">Dysk SSD Crucial MX200 500GB SATA3 (CT500MX200SSD6) Darmowy odbi&#243;r w 19 miastach! Raty od 29,00 z&#322;<"+"/div>\n";
ifc += "<"+"div class=\"desc\" data-ellipsis=\"multiline\"><"+"/div>\n";
ifc += "<"+"div class=\"priceDesc\">\n";
ifc += "<"+"span class=\"priceType\">rrp<"+"/span>\n";
ifc += "<"+"del class=\"origPrice\"><"+"/del>\n";
ifc += "<"+"span class=\"price\">718,58 z&#322;<"+"/span>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/a>\n";
ifc += "<"+"/div>\n";
ifc += "\n";
ifc += "<"+"div class=\"cto_product\">\n";
ifc += "<"+"a href=\"http://cat.nl.eu.criteo.com/delivery/ck.php?cppv=1&cpp=r6Eb%2F3xQVWQyN0NISHNTdy9SbCs3VzIzVGJEMjVKMUZjUFRwSXNTVVRCVHM2UzFxdXR2VmROSXAyUXJtV01ZN1hsUk9pMEZDOG9PZWw2YkZ6RlFlZjNuTVk3MFhoV292SmNTbnVhRUU3Z1NEc1U4ZlhYVXNjZW5EYmRVYjFMWEhZMlRYUW1OWnZXam1SUGhlN2NvK3VvTytmRHJxNm5ZY21YVTZiMHQ0YUtlbHNybkI5MW5hTEx2eG1BRnZObExFTjJuclVGeFpYeUxkam1McWUzYUFSTy9KZ3VyMGxrYWFoZkQ3YllhVUpUV01vY0tYc3dzNHV4K3pnWVM2TjlWVzhGWDhSemxuZGJUbXIyUVFzRUc3ZzlpanVVYWc5ZElFTVNlNExPQjFvVzJBTE5RZz18&maxdest=http%3A%2F%2Fwww.morele.net%2Fkarta-graficzna-karta-graficzna-gigabyte-geforce-gtx-1070-8gb-gddr5-256-bit-hdmi-dvi-d-3x-dp-box-gv-n1070g1-gaming-8gd-774260%2F%3Futm_source%3Dcriteo.com%26utm_medium%3Dbaner%26utm_content%3D300x250%26utm_campaign%3Dremarketing_criteo\" target=\"_blank\" >\n";
ifc += "<"+"div class=\"imgholder\">\n";
ifc += "<"+"img src=\"http://pix.nl.eu.criteo.net/img/img?c=1&cb=1&h=400&i=15285-774260&m=0&q=80&r=0&u=https%3A%2F%2Fimages.morele.net%2Fi256%2F774260_0_i256.png&w=400&s=dcQq--WYR9cUR_AMFreoh92P\">\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div class=\"details\">\n";
ifc += "<"+"div class=\"title\" data-ellipsis=\"multiline\">Karta graficzna Gigabyte GeForce GTX 1070 8GB GDDR5 (256 bit) HDMI, DVI-D, 3x DP, BOX (GV-N1070G1 GAMING-8GD) Szybka dostawa!  Darmowy odbi&#243;r w 19 miastach! Raty od 85,00 z&#322;<"+"/div>\n";
ifc += "<"+"div class=\"desc\" data-ellipsis=\"multiline\"><"+"/div>\n";
ifc += "<"+"div class=\"priceDesc\">\n";
ifc += "<"+"span class=\"priceType\">rrp<"+"/span>\n";
ifc += "<"+"del class=\"origPrice\"><"+"/del>\n";
ifc += "<"+"span class=\"price\">2.089 z&#322;<"+"/span>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/a>\n";
ifc += "<"+"/div>\n";
ifc += "\n";
ifc += "<"+"div class=\"cto_product\">\n";
ifc += "<"+"a href=\"http://cat.nl.eu.criteo.com/delivery/ck.php?cppv=1&cpp=gcOPfnxQVWQyN0NISHNTdy9SbCs3VzIzVGJEMjVKMUZjUFRwSXNTVVRCVHM2UzFxdXR2VmROSXAyUXJtV01ZN1hsUk9pMEZDOG9PZWw2YkZ6RlFlZjNuTVk3MFhoV292SmNTbnVhRUU3Z1NEc1U4ZlhYVXNjZW5EYmRVYjFMWEhZMlRYUW1OWnZXam1SUGhlN2NvK3VvTytmRG9KYUpwZ1JLWXIrT0VsYjg0VDYxcGRWUHZBMXdoSUFjTjVMY09vTmU3TVhhZ1dlWU5NMCtOQjc1eWdoU0FrbkkwaTJFaFU4MEQ4Ti9wVHBXb2oxRlJQcmlJTWFwVU5qaENsUEdTTlIrbUdJTFkrTkJCTDM1bit3MGNqVGhuMmdSZENHaUZHdXhkcjgvb2xuNEhxd1ZNOD18&maxdest=http%3A%2F%2Fwww.morele.net%2Fzasilacz-zasilacz-xfx-black-edition-xtr-650w-fully-modular-135mm-80-gold-p1-650b-befx-628156%2F%3Futm_source%3Dcriteo.com%26utm_medium%3Dbaner%26utm_content%3D300x250%26utm_campaign%3Dremarketing_criteo\" target=\"_blank\" >\n";
ifc += "<"+"div class=\"imgholder\">\n";
ifc += "<"+"img src=\"http://pix.nl.eu.criteo.net/img/img?c=1&cb=1&h=400&i=15285-628156&m=0&q=80&r=0&u=https%3A%2F%2Fimages.morele.net%2Fi256%2F628156_0_i256.jpg&w=400&s=WTI3rd23X6CC2XRSOWfjgSd2\">\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div class=\"details\">\n";
ifc += "<"+"div class=\"title\" data-ellipsis=\"multiline\">Zasilacz XFX Black Edition XTR 650W Fully Modular 135mm 80+ Gold (P1-650B-BEFX) Szybka dostawa!  Darmowy odbi&#243;r w 19 miastach! Raty od 16,00 z&#322;<"+"/div>\n";
ifc += "<"+"div class=\"desc\" data-ellipsis=\"multiline\"><"+"/div>\n";
ifc += "<"+"div class=\"priceDesc\">\n";
ifc += "<"+"span class=\"priceType\">rrp<"+"/span>\n";
ifc += "<"+"del class=\"origPrice\"><"+"/del>\n";
ifc += "<"+"span class=\"price\">405,30 z&#322;<"+"/span>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/a>\n";
ifc += "<"+"/div>\n";
ifc += "\n";
ifc += "<"+"/div>\n";
ifc += "<"+"!-- PRIVACY[BOTTOM:RIGHT] -->\n";
ifc += "<"+"div class=\"footer\"> \n";
ifc += "                            <"+"div class=\'privacy\'>\n";
ifc += "                                <"+"a href=\'http://info.criteo.com/pac/privacy/informations?infonorm=3&amp;partner=15285&amp;campaignid=61975&amp;zoneid=349170&amp;bannerid=3174075&amp;displayid=0802fd96a4\' target=\'_blank\'><"+"/a>\n";
ifc += "                            <"+"/div> <"+"a href=\"http://cat.nl.eu.criteo.com/delivery/ck.php?cppv=1&amp;cpp=WpNQYHxQVWQyN0NISHNTdy9SbCs3VzIzVGJEMjVKMUZjUFRwSXNTVVRCVHM2UzFxdXR2VmROSXAyUXJtV01ZN1hsUk9pMEZDOG9PZWw2YkZ6RlFlZjNuTVk3MFhoV292SmNTbnVhRUU3Z1NEc1U4ZlhYVXNjZW5EYmRVYjFMWEhZMlRYUW1OWnZXam1SUGhlN2NvK3VvTytmRHJ1TmJ4blBrVzNvWGkzeEZFQzlLUFhWcHBGQ0VONHpsYm9XUWl5RFpCMXBpTG9zUVlpa1ZEMnV6Z1ZPRmx5TVFOQ1N0bEJFQWtJYkFEVXR2bG4vWEppcTU5S1Q4TDZQdTdQem9ZRHE2cGtaSk5lamtlMXFVQkRESm1CY1FlQndEUT09fA%3D%3D&amp;maxdest=http%3A%2F%2Fwww.morele.net%3Futm_source%3Dcriteo.com%26utm_medium%3Dbaner%26utm_content%3D300x250%26utm_campaign%3Dremarketing_criteo\" target=\"_blank\" class=\"adUrl\" >Ads by morele.net<"+"/a>\n";
ifc += "<"+"/div> <"+"/div>\n";
ifc += "<"+"style>#cto_banner_content .privacy {\n";
ifc += "                    width:77px;\n";
ifc += "                    float:right;\n";
ifc += "                    text-align:right;\n";
ifc += "                }\n";
ifc += "\n";
ifc += "                #cto_banner_content .privacy a {\n";
ifc += "                    display:inline-block;\n";
ifc += "                    width:19px;\n";
ifc += "                    height:15px;\n";
ifc += "                    background-image:url(http://static.eu.criteo.net/flash/icon/nai_small.png);\n";
ifc += "                }\n";
ifc += "\n";
ifc += "                #cto_banner_content .privacy a:hover {\n";
ifc += "                    width:77px;\n";
ifc += "                    height:15px;\n";
ifc += "                    background-image:url(http://static.eu.criteo.net/flash/icon/nai_big.png);\n";
ifc += "                }<"+"/style>\n";
ifc += "<"+"script type=\'text/javascript\'>(function() { var arrayEquals = function (a, b) {\n";
ifc += "                if(a.length != b.length) return false;\n";
ifc += "                a = a.sort();\n";
ifc += "                b = b.sort();\n";
ifc += "                for(var i = 0; i <"+" a.length; ++i) {\n";
ifc += "                    if (a[i] != b[i]) return false;\n";
ifc += "                }\n";
ifc += "                return true;\n";
ifc += "            };\n";
ifc += "\n";
ifc += "            var arrayIterate = function (a, fct) {\n";
ifc += "                var len = a.length;\n";
ifc += "                for(var i = 0; i <"+" len; ++i) {\n";
ifc += "                    fct(a[i], i); \n";
ifc += "                }\n";
ifc += "             };\n";
ifc += "   \n";
ifc += "            var arrayWhere = function (a, fct) {\n";
ifc += "                b = [];\n";
ifc += "                arrayIterate(a, function(elt, index) {\n";
ifc += "                    if(fct(elt, index)) b.push(elt);\n";
ifc += "                });\n";
ifc += "                return b;\n";
ifc += "             };\n";
ifc += "      \n";
ifc += "            var arrayMap = function (a, fct) {\n";
ifc += "                b = [];\n";
ifc += "                arrayIterate(a, function(elt, index) {\n";
ifc += "                    b[index] = fct(elt, index);\n";
ifc += "                });\n";
ifc += "                return b;\n";
ifc += "            };\n";
ifc += "\n";
ifc += "            var multilineEllipsis = function (div) {\n";
ifc += "                var t = div.textContent || div.innerText;\n";
ifc += "                var d = document.createElement(\'div\');\n";
ifc += "                var i = 0;    \n";
ifc += "                d.style.width = div.offsetWidth + \'px\';\n";
ifc += "                d.style.visibility = \"hidden\";\n";
ifc += "                div.appendChild(d);\n";
ifc += "\n";
ifc += "                while(d.offsetHeight <"+"= div.offsetHeight && i <"+" t.length) {\n";
ifc += "                    d.textContent = d.innerText = t.substr(0, i) + \'...\';\n";
ifc += "                    ++i;\n";
ifc += "                }\n";
ifc += "\n";
ifc += "                div.removeChild(d);\n";
ifc += "                if(i != t.length) div.textContent = div.innerText = t.substr(0, i-2) + \'...\';\n";
ifc += "            };\n";
ifc += "\n";
ifc += "            (function() {\n";
ifc += "                var c = document.getElementById(\'cto_banner_content\');\n";
ifc += "                var isMultilineEllipsis = function(elt) { return elt.getAttribute(\'data-ellipsis\') == \'multiline\'; };\n";
ifc += "                arrayIterate(arrayWhere(c.getElementsByTagName(\'*\'), isMultilineEllipsis), multilineEllipsis);\n";
ifc += "            })(); })();<"+"/script>\n";
ifc += "<"+"script type=\"text/javascript\">\n";
ifc += "(function() { var getElts = function(className, domElem) { var desc = []; if (document.getElementsByClassName) { desc = domElem.getElementsByClassName(className); } else { var elem = domElem.getElementsByTagName(\'*\'); for (var x = 0; x <"+" elem.length; x++) { if ((\' \' + elem[x].className + \' \').indexOf(\' \' + className + \' \') > -1) desc.push(elem[x]); } } return desc; }; var truncate = function(div, maxCharacter) { var t = div.textContent || div.innerText || \"\"; var trimmed = t.replace(\'\\\\n\', \'\').replace(/^ +| +$/g, \'\'); if(trimmed.length > maxCharacter) div.textContent = div.innerText = trimmed.substr(0, maxCharacter-3) + \'...\'; }; var products = getElts(\"cto_product\", document); for(var x = 0; x <"+" products.length; ++x) { var price = getElts(\"priceDesc\", products[x])[0]; var priceType = getElts(\"priceType\", price)[0]; var priceNumber = getElts(\"price\", price)[0]; var priceOrig = getElts(\"origPrice\", price)[0]; var priceTypeText = priceType.textContent || priceType.innerText || \"\"; if (priceNumber.innerHTML == \"\" || priceNumber.innerHTML.length > 14) { price.removeChild(priceOrig); price.removeChild(priceType); price.removeChild(priceNumber); } else if (priceTypeText.indexOf(\"__\") == 0) { var altprice = priceTypeText.replace(/_/g, \"\"); priceType.innerHTML = altprice; price.removeChild(priceOrig); } else if (priceTypeText == \"rrp\") { price.removeChild(priceType); } }\n";
ifc += "})(); <"+"/script><"+"/div><"+"div style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'>\n";
ifc += "<"+"iframe id=\'if0802fd96a4\' name=\'if0802fd96a4\' width=\'1px\' height=\'1px\'><"+"/iframe>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div id=\'beacon_0802fd96a4\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'>\n";
ifc += "<"+"img width=\"0\" height=\"0\" src=\"http://cat.nl.eu.criteo.com/delivery/lg.php?cppv=1&cpp=l9u7RHxQVWQyN0NISHNTdy9SbCs3VzIzVGJEMjVKMUZjUFRwSXNTVVRCVHM2UzFxdXR2VmROSXAyUXJtV01ZN1hsUk9pMEZDOG9PZWw2YkZ6RlFlZjNuTVk3MFhoV292SmNTbnVhRUU3Z1NEc1U4ZlhYVXNjZW5EYmRVYjFMWEhZMlRYUVJvcm81NTRFUnRUOTV1MTVYdTlycGhQT1BYR3RVQTV6YmlpQzB0dkZZUkx4MHFvbUIvc3orRzZzazVvbUphNU5idUpnNHRhblBiSGxacmJQUjhJM0U0UTNzU0NUazV6QStmVjEza2srdUtWY1g0Y3NxWFU0eVh2b0ZaWHBDcXVGVlZCNmcwV3J5YXFKYjFZekNNYkJhbDZaZmtaSFJMcExlMlk4NTdsYnNuZz18\"/>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/body>\n";
ifc += "<"+"/html>\n";

var fillIframe = function(ifrd) {
    var getDocument = function(iframe) {
        var result_document = iframe.contentWindow || iframe.contentDocument;
        if (result_document && result_document.document)
            result_document = result_document.document;
        return result_document;
    };
    var c = getDocument(ifrd);
    if (c) {
        c.open();
        c.write(ifc);
        c.close();
    }
};


var maxRetryAttempts = 100;
var loaded = false;
var pollIframe = function() {
    var ifrd = document.getElementById('cto_iframe_0802fd96a4');
    if (ifrd && isIE) {
         ifrd.onload = function() {
            if(!loaded) {
                loaded = true;
                fillIframe(ifrd);
            }
        };
    } else if (ifrd) {
        loaded = true;
        fillIframe(ifrd);
    } else if (maxRetryAttempts-- > 0) {
        setTimeout(pollIframe, 10);
    }
};pollIframe();
})();
